title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: All things that make a Blocher think.

# social links
twitter_username: @cblocher
github_username:  cblocher

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
